apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: canary-example
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - overlay: openshift
        gitRepo: https://github.com/christianh814/ocp-sm-ar
        appPath: canary/overlays
        appName: canary-app
        appBranch: main
        appNamespace: canary
      - overlay: openshift
        gitRepo: https://github.com/christianh814/ocp-sm-ar
        appPath: sm-config/overlays
        appName: sm-config
        appBranch: main
        appNamespace: istio-system
  template:
    metadata:
      name: '{{appName}}'
    spec:
      ignoreDifferences:
      - group: networking.istio.io
        kind: VirtualService
        jsonPointers:
        - /spec/http/0
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - ApplyOutOfSyncOnly=true
        retry:
          limit: 7
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
      source:
        repoURL: '{{gitRepo}}'
        targetRevision: '{{appBranch}}'
        path: '{{appPath}}/{{overlay}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{appNamespace}}'
